export const projectContent = [
  {
    id: 1,
    title: "TrashArtify",
    description:
      "A finalist project for Hack@10. TrashArtify is all about empowering eco-creativity. Scan recyclables, generate AI craft ideas, and create sustainable handicraft.",
    techStack: ["React", "Flask", "Stable Diffusion", "YOLOv8"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 2,
    title: "Inbound Operation in Automated Warehouse",
    description: "A research-based final year project investigating the utilization of synthetic data within a warehouse environment, specifically focusing on determining suitable occupancy levels and optimizing rearrangement strategies.",
    techStack: ["Python"],
    imageUrl: "environment.png",
    category: "ml",
  },
  {
    id: 3,
    title: "Project 3",
    description: "Description of Project 3",
    techStack: ["Angular", "Firebase"],
    imageUrl: "environment.png",
    category: "mobile",
  },
  {
    id: 4,
    title: "Project 4",
    description: "Description of Project 4",
    techStack: ["React Native", "MongoDB"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 5,
    title: "Project 5",
    description: "Description of Project 5",
    techStack: ["Flutter", "Firebase"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 6,
    title: "Project 6",
    description: "Description of Project 6",
    techStack: ["Vue.js", "Node.js"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 7,
    title: "Project 7",
    description: "Description of Project 7",
    techStack: ["React", "MongoDB"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 8,
    title: "Project 8",
    description: "Description of Project 8",
    techStack: ["Angular", "Express"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 9,
    title: "Project 9",
    description: "Description of Project 9",
    techStack: ["React Native", "Firebase"],
    imageUrl: "environment.png",
    category: "web",
  },
  {
    id: 10,
    title: "Project 10",
    description: "Description of Project 10",
    techStack: ["Flutter", "Node.js"],
    imageUrl: "environment.png",
    category: "mobile",
  },
];
